/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.43
 * Generated at: 2025-10-03 09:02:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class addnotes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1759415740583L));
    _jspx_dependants.put("/form.jsp", Long.valueOf(1759482020900L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css\" integrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<title>ADD_NOTES</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	 <div class=\"navContainer\">\r\n");
      out.write("   		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<title>NAVBAR</title>\r\n");
      out.write("\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"./css/navbar.css\">\r\n");
      out.write(" <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write(" <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write(" <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <header class=\"site-header\">\r\n");
      out.write("    <nav class=\"navbar\" aria-label=\"Main navigation\">\r\n");
      out.write("      <span class=\"brand\" aria-label=\"Flowbite home\">\r\n");
      out.write("        <img class=\"brand-logo\" src=\"media/sticky-notes.png\" alt=\"Note Taker logo\" />\r\n");
      out.write("        <span class=\"brand-text\">NOTE TAKER</span>\r\n");
      out.write("      </span>\r\n");
      out.write("\r\n");
      out.write("      <button class=\"menu-toggle\" aria-label=\"Open menu\" aria-expanded=\"false\" aria-controls=\"mobile-menu\">\r\n");
      out.write("        <svg viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\">\r\n");
      out.write("          <line x1=\"3\" y1=\"6\" x2=\"21\" y2=\"6\"></line>\r\n");
      out.write("          <line x1=\"3\" y1=\"12\" x2=\"21\" y2=\"12\"></line>\r\n");
      out.write("          <line x1=\"3\" y1=\"18\" x2=\"21\" y2=\"18\"></line>\r\n");
      out.write("        </svg>\r\n");
      out.write("      </button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"nav-links\" role=\"list\">\r\n");
      out.write("        <li><a class=\"nav-link active\" href=\"index.jsp\">HOME</a></li>\r\n");
      out.write("        <li><a class=\"nav-link\" href=\"addnotes.jsp\">ADD NOTE</a></li>\r\n");
      out.write("        <li><a class=\"nav-link\" href=\"#services\">SHOW NOTES</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <form class=\"search\" role=\"search\" aria-label=\"Site\">\r\n");
      out.write("        <span class=\"search-icon\" aria-hidden=\"true\">\r\n");
      out.write("          <svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\">\r\n");
      out.write("            <circle cx=\"11\" cy=\"11\" r=\"8\"></circle>\r\n");
      out.write("            <line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\"></line>\r\n");
      out.write("          </svg>\r\n");
      out.write("        </span>\r\n");
      out.write("        <input class=\"search-input\" type=\"search\" placeholder=\"Search...\" aria-label=\"Search\" />\r\n");
      out.write("      </form>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </header>\r\n");
      out.write("  <ul id=\"mobile-menu\" class=\"mobile-menu\" role=\"list\" hidden>\r\n");
      out.write("    <li><a class=\"nav-link active\" href=\"#\">HOME</a></li>\r\n");
      out.write("    <li><a class=\"nav-link\" href=\"#about\">ADD NOTE</a></li>\r\n");
      out.write("    <li><a class=\"nav-link\" href=\"#services\">SHOW NOTES</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  <script>\r\n");
      out.write("  (function(){\r\n");
      out.write("    var toggle = document.querySelector('.menu-toggle');\r\n");
      out.write("    var menu = document.getElementById('mobile-menu');\r\n");
      out.write("    if(!toggle || !menu) return;\r\n");
      out.write("    toggle.addEventListener('click', function(){\r\n");
      out.write("      var isOpen = toggle.getAttribute('aria-expanded') === 'true';\r\n");
      out.write("      toggle.setAttribute('aria-expanded', String(!isOpen));\r\n");
      out.write("      menu.hidden = isOpen;\r\n");
      out.write("    });\r\n");
      out.write("    // Close menu when clicking a link\r\n");
      out.write("    menu.addEventListener('click', function(e){\r\n");
      out.write("      var target = e.target;\r\n");
      out.write("      if(target && target.tagName === 'A'){\r\n");
      out.write("        toggle.setAttribute('aria-expanded','false');\r\n");
      out.write("        menu.hidden = true;\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  })();\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   	</div>\r\n");
      out.write("   	\r\n");
      out.write("   \r\n");
      out.write("   	<p>this is notes page</p>\r\n");
      out.write("   	\r\n");
      out.write("   <!-- NOTE FORM -->\r\n");
      out.write("   \r\n");
      out.write("  <div class=\"formContainer\">\r\n");
      out.write("   		");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Contact Form</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/form.css\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Alan+Sans:wght@300..900&family=Bungee+Inline&family=Fugaz+One&family=Ribeye+Marrow&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-card\">\r\n");
      out.write("<form action=\"SaveNotesServlet\" method=\"post\" class=\"contact-form\" novalidate>\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label for=\"title\">TITLE</label>\r\n");
      out.write("<input type=\"text\" required id=\"title\" name=\"title\" placeholder=\"\" />\r\n");
      out.write("<small class=\"hint\" aria-hidden=\"true\"></small>\r\n");
      out.write("<div class=\"error\" aria-live=\"polite\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label for=\"content\">CONTENT</label>\r\n");
      out.write("<textarea id=\"content\" name=\"content\" rows=\"3\" required></textarea>\r\n");
      out.write("<div class=\"error\" aria-live=\"polite\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<button type=\"submit\" class=\"submit-btn\">SUBMIT</button>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("   	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
